
# 连接远程pokechien_do
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://129.88.175.104:5432/bd_zhaoj
spring.datasource.username=postgres
spring.datasource.password=password
