services:

   # postgres + psotgis
   postgis-16-3.4:
       image: postgis/postgis:16-3.4
       ports:  #outside:inside(container)
            - 4202:5432
       networks:
            - shared-network 
       volumes:
            - ./vol_data:/mnt:rw  # montage dir vol_data du hôte sur /mnt du conteneur
            - pgdata:/var/lib/postgresql/data
       environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
       container_name: postgis

   # pgadmin4
   pgadmin4:
       image: dpage/pgadmin4
       container_name: pgadmin
       environment: 
        - PGADMIN_DEFAULT_EMAIL=admin@admin.fr
        - PGADMIN_DEFAULT_PASSWORD=password
       ports:
        - 4201:80  #outside:inside(container)
       networks:
        - shared-network
       volumes:
         - pgadminData:/var/lib/pgadmin/
         - ./pgadminstorage:/var/lib/pgadmin/storage/admin_admin_fr  #- C:/Users/philippe/Desktop/POOJava/PI_POC:/var/lib/pgadmin/data
       depends_on: 
         - postgis-16-3.4

volumes:
    pgdata:
    pgadminData:
networks:
    shared-network:
