# data source configurée pour une base tournant sur un serveur local, pi_poc est le nom de la base
spring.datasource.url=jdbc:postgresql://localhost:5432/pi_poc
spring.datasource.username=springboot
spring.datasource.password=postgres!*
#
# Pour utliser votre base sur les serveur de l'IUGA commenter les lignes au dessus
# décommentez les lignes ci-dessous et remplacez xxxxx par votre identifiant AGALAN
# et yyyyyyy par votre mot de passe
#
# spring.datasource.url=jdbc:postgresql://129.88.175.104:5432/bd_xxxxx
# spring.datasource.username=xxxxx
# spring.datasource.password=yyyyyyy

